service: auth0-APIGateway-customAuthorizer

provider:
  name: aws
  runtime: nodejs6.10
  cfLogs: true
  timeout: 20
  stage: dev
  region: ap-northeast-1
  environment:
    AUTH0_DOMAIN: ${file(./config.yml):auth0Domain}
    AUDIENCE: ${file(./config.yml):audience}
    JWKS_URI: ${file(./config.yml):jwksUri}
    TOKEN_ISSUER: ${file(./config.yml):tokenIssuer}

plugins:
  - serverless-webpack

functions:
  customAuthorizer:
    handler: handler.auth
  public:
    handler: handler.public
    events:
      - http:
          path: public
          method: get
          integration: lambda
          cors: true
  private:
    handler: handler.private
    events:
      - http:
          path: private
          method: get
          integration: lambda
          authorizer: customAuthorizer
          cors: true
