service: auth0-APIGateway-customAuthorizer

provider:
  name: aws
  runtime: nodejs6.10
  cfLogs: true
  timeout: 20
  stage: dev
  region: ap-northeast-1
  environment:
    AUTH0_CLIENT_ID: ${file(./config.yml):auth0ClientId}
    AUTH0_CLIENT_SECRET: ${file(./config.yml):auth0ClientSecret}

functions:
  customAuthorizer:
    handler: handler.auth
  public:
    handler: handler.public
    events:
      - http:
          path: public
          method: get
          integration: lambda
          cors: true
  private:
    handler: handler.private
    events:
      - http:
          path: private
          method: get
          integration: lambda
          authorizer: customAuthorizer
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
